In [1]:
import numpy as np
import matplotlib.pyplot as plt

### 기억할 패턴

In [2]:
A1 = np.array([1,1,1,0]).T
A2 = np.array([1,1,0,0]).T

In [3]:
print(A1, A2)

[1 1 1 0] [1 1 0 0]


### 양극화

In [4]:
X1 = 2*A1 - 1
X2 = 2*A2 - 1

In [5]:
print(X1, X2)

[ 1  1  1 -1] [ 1  1 -1 -1]


### 가중치행렬

In [6]:
W1 = np.outer(X1, X1)
W2 = np.outer(X2, X2)
I = np.eye(4)

W = W1 + W2 - 2*1

In [17]:
W

array([[ 0,  0, -2, -4],
       [ 0,  0, -2, -4],
       [-2, -2,  0, -2],
       [-4, -4, -2,  0]])

### 테스트패턴

In [8]:
B = np.array([0,1,0,0]).T

### 임계값

In [18]:
th1 = -(1/2)*W[0:].sum()
th2 = -(1/2)*W[0:].sum()
th3 = -(1/2)*W[0:].sum()
th4 = -(1/2)*W[0:].sum()